version: "3.6"
services:
  app:
    container_name: app
    restart: always
    build:
      context: test-microservice/
    ports:
      - "8080"
    links:
      - rabbitmq
      - mongodb
    environment:
      - NODE_ENV=production

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    hostname: rabbitmq
    volumes:
      - ./data/rabbitmq:/data/
    ports:
      - "5672"

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017"
